spring:
  output:
    ansi:
      enabled: "always"
  application:
    name: "Spring bean injection demo"
  datasource:
    jdbc-url: "jdbc:postgresql://localhost:5432/springBeanInjectionDemo"
    username: postgres
    password: postgres

management:
  notification-service: "email"
  persistence:
    service: "postgres"

logging:
  level:
    root: "INFO"